# Simbiosis Simulation Configuration
# Configure every part of the simulation using the config.yml file

# World configuration
# Quadrant Rows is how many rows and columns they are. If there's 4, then the world will be a 4x4 world
# Quadrant Size is how large in pixels each quadrant will be
world:
  quadrant_rows: 4
  quadrant_size: 100

# Startup configuration
# Choose how many species there are and how many creatures start in each species
# Choose how many food clusters there are when beginning the simulation
startup:
  species: 10
  creatures: 100
  food_clusters: 30

# Mutation configuration
# Choose the type of mutation, either: 'additive' or 'multiplicative'
# Mutation Value is used in both Mutation Types.
#
# Additive Mutation with a Value of 0.2:
# 1. Choose a random number from -0.2 to 0.2
# 2. Add that number to the gene
#
# Multiplicative Mutation with a Value of 0.2:
# 1. Choose a random number from 0.8 to 1.2
# 2. Multiply the gene by that number
mutation:
  type: 'additive'
  value: 0.2


